#!/bin/bash

# first put all js together

rm index.js

find $1 \
  -name '*.js' \
  -not -name 'index.js' \
  -exec cat {} \; \
    >> index.js

cd $1
cat index.js >> ../index.js

cd - 
#cat index.js

# for esp
espruino -p /dev/ttyUSB0 -b 115200 index.js #-e "save()"
# for microbit
#espruino -p /dev/ttyACM0 -b 9600 index.js
